import { z } from "zod";
import type { OrganisationKind } from "./organisation";
import type { Messages } from "./i18n/ja";

/**
 * ドキュメント生成のテンプレート。
 *
 * テンプレートは**システムの中で作る**（Wordファイルは使わない）。
 * 中身はここで決めた形の JSON で、`document_templates.content` に入る。
 *
 * ## なぜ Word ではないのか
 *
 * Word に差し込む形だと、`{product.cod}` のような打ち間違いを
 * 登録のときに検査する仕組みが別に要る。
 * **項目を一覧から選ばせれば、無い項目は書きようがない。**
 *
 * ## 出す形に引きずられないこと
 *
 * ここに置くのは「何を、どの順で出すか」だけ。
 * HTML にするのか .docx にするのかは、出す側（レンダラ）が決める。
 * **JSON に出力形式のことを書かない。**書くと、出し先が増えるたびに
 * 作ったテンプレートを作り直すことになる。
 */

/** テンプレートが何を1件受け取るか */
/**
 * 様式の作りかた。
 *
 * - `BLOCK` … 画面でブロックを積む。中身はこのファイルの `DocumentContent`
 * - `XLSX` / `DOCX` … Excel・Word のファイルを預かり、**差込札に値を埋めて返す**。
 *   罫線・セルの結合・ヘッダー・ロゴがそのまま使えるので、
 *   取引先から来た調査票の形をそのまま出せる（札の書き方は `doc-tags.ts`）
 */
export const DOCUMENT_TEMPLATE_KINDS = ["BLOCK", "XLSX", "DOCX"] as const;
export type DocumentTemplateKind = (typeof DOCUMENT_TEMPLATE_KINDS)[number];

/**
 * テンプレートの対象。
 *  PRODUCT / SUBSTANCE … 製品・物質 1 件につき 1 枚
 *  ORGANISATION … 組織（取引先など）1 件につき 1 枚（2026-09-16 指示）
 *  NONE … 対象なし（汎用）。共通の項目だけで 1 枚（送付状・案内状など）
 */
export const DOCUMENT_TARGETS = ["PRODUCT", "SUBSTANCE", "ORGANISATION", "NONE"] as const;
export type DocumentTarget = (typeof DOCUMENT_TARGETS)[number];

/** 対象を 1 件ずつ選ぶ種類か（NONE だけは選ばずに作る） */
export function targetHasRows(target: DocumentTarget): boolean {
  return target !== "NONE";
}

/**
 * 差込項目。**エディタの選択肢と、差し込む側の両方がここを見る。**
 * 片方にしか無い項目ができると、選べるのに空欄になる（またはその逆）。
 */
export interface DocumentField {
  /** `product.code` のような鍵。テンプレート JSON に入る */
  key: string;
  /** どの対象のときに選べるか。`*` はどの対象でも（作成日時・会社・宛先など） */
  target: DocumentTarget | "*";
  /** 選択肢に出す名前。画面の言語で出し分けるので2つ持つ */
  labelJa: string;
  labelEn: string;
}

/**
 * 使える差込項目の一覧。
 *
 * **画面が出しているものだけを並べる。**画面に無い値をここに足すと、
 * 帳票のためだけにデータを引く道ができてしまい、画面と食い違う元になる。
 */
export const DOCUMENT_FIELDS: DocumentField[] = [
  // --- 共通（どちらの対象でも出せるもの） ---
  { key: "doc.generatedAt", target: "*", labelJa: "作成日時", labelEn: "Generated at" },
  { key: "doc.generatedBy", target: "*", labelJa: "作成者", labelEn: "Generated by" },
  { key: "doc.version", target: "*", labelJa: "法規制バージョン", labelEn: "Version" },

  // --- 製品 ---
  { key: "product.code", target: "PRODUCT", labelJa: "製品コード", labelEn: "Product code" },
  { key: "product.nameJa", target: "PRODUCT", labelJa: "日本語名称", labelEn: "Name (JA)" },
  { key: "product.nameEn", target: "PRODUCT", labelJa: "英語名称", labelEn: "Name (EN)" },
  { key: "product.modelName", target: "PRODUCT", labelJa: "型式", labelEn: "Model" },
  { key: "product.useName", target: "PRODUCT", labelJa: "用途", labelEn: "Use" },
  { key: "product.note", target: "PRODUCT", labelJa: "備考", labelEn: "Note" },
  {
    key: "product.judgementCount",
    target: "PRODUCT",
    labelJa: "該当した規制区分の数",
    labelEn: "Applicable categories",
  },

  // --- 物質 ---
  { key: "substance.code", target: "SUBSTANCE", labelJa: "物質コード", labelEn: "Substance code" },
  { key: "substance.casNumber", target: "SUBSTANCE", labelJa: "CAS番号", labelEn: "CAS number" },
  { key: "substance.nameJa", target: "SUBSTANCE", labelJa: "日本語名", labelEn: "Name (JA)" },
  { key: "substance.nameEn", target: "SUBSTANCE", labelJa: "英語名", labelEn: "Name (EN)" },
  { key: "substance.note", target: "SUBSTANCE", labelJa: "備考", labelEn: "Note" },

  /*
    作った人の会社と部署。**いつも作った人のもの。**
    （以前は「差出人」と呼び、権限があれば別の会社に差し替えられたが、
    2026-09-13 指示で「所属する」と「任意の」に分けた）
  */
  { key: "org.name", target: "*", labelJa: "所属する会社名", labelEn: "Your company" },
  { key: "org.group", target: "*", labelJa: "所属部署", labelEn: "Your department" },
  /*
    任意の会社と部署。**作るときに選ぶ。**自分が所属していない組織も選べる。
    様式がこの項目を使っているときだけ、作る画面に選ぶ欄が出る
  */
  { key: "pick.company", target: "*", labelJa: "任意の会社名", labelEn: "Chosen company" },
  { key: "pick.department", target: "*", labelJa: "任意の部署", labelEn: "Chosen department" },

  /*
    宛先。**「宛先を使う」印の付いた様式でだけ選ばせる。**
    印の無い様式に置いても空欄になる（社内文書に宛名は要らない）
  */
  { key: "to.name", target: "*", labelJa: "宛先の名称", labelEn: "Recipient" },

  /*
    対象が組織のとき（2026-09-16 指示）。取引先ごとの案内状・調査依頼など。
    自由項目は `target.item.<項目名>`（会社の自由項目と同じ仕組み。無い項目は空欄）
  */
  {
    key: "organisation.code",
    target: "ORGANISATION",
    labelJa: "組織コード",
    labelEn: "Organisation code",
  },
  {
    key: "organisation.name",
    target: "ORGANISATION",
    labelJa: "組織の名称",
    labelEn: "Organisation name",
  },
  {
    key: "organisation.nameEn",
    target: "ORGANISATION",
    labelJa: "組織の名称（英語）",
    labelEn: "Organisation name (EN)",
  },
  {
    key: "organisation.kind",
    target: "ORGANISATION",
    labelJa: "組織の種別",
    labelEn: "Organisation kind",
  },
];

/** 対象の組織の自由項目につく頭（対象が組織のとき） */
export const TARGET_ORG_ITEM_PREFIX = "target.item.";

export function targetOrgItemField(label: string): DocumentField {
  return {
    key: `${TARGET_ORG_ITEM_PREFIX}${label}`,
    target: "ORGANISATION",
    labelJa: `対象の組織の${label}`,
    labelEn: `Organisation: ${label}`,
  };
}

/** 差出人の自由項目につく頭。この後ろに項目名がそのまま付く */
export const ORG_ITEM_PREFIX = "org.item.";

/** 宛先の自由項目につく頭 */
export const RECIPIENT_ITEM_PREFIX = "to.item.";

/**
 * 組織ブロックで「組織の名称そのもの」を指す項目名。
 * **項目名と同じ並びで選ばせる**ので、名前の欄を別に作らない。
 * 組織の項目名として人が打たない形にしてある（以前は \u0000 を使っていたが、
 * PostgreSQL の JSON に入らず保存で落ちた）
 */
export const ORG_NAME_ITEM = "$name$";

/** 組織ブロックが引く値の鍵。組織ごとに違うので id を挟む */
export function orgBlockKey(organisationId: string, item: string): string {
  return item === ORG_NAME_ITEM
    ? `orgOf.${organisationId}.name`
    : `orgOf.${organisationId}.item.${item}`;
}

/**
 * 様式が使っている差込項目の鍵。文章・見出しの中の差込と、項目の並びの項目を集める。
 * 「任意の会社名」「任意の部署」を使っているときだけ、作る画面で選ばせるために要る
 */
export function fieldKeysIn(content: DocumentContent): Set<string> {
  const out = new Set<string>();
  for (const b of content.blocks) {
    if (b.kind === "heading" || b.kind === "text") {
      for (const line of b.lines) {
        for (const s of line.spans) if (s.kind === "field" && s.field) out.add(s.field);
      }
    } else if (b.kind === "fields") {
      for (const it of b.items) if (it.field) out.add(it.field);
    }
  }
  return out;
}

/** 作るときに選ぶ組織の鍵 */
export const PICK_COMPANY_KEY = "pick.company";
export const PICK_DEPARTMENT_KEY = "pick.department";

/** テンプレートが名指ししている組織のid。差し込む前に読み込むために要る */
export function organisationIdsIn(content: DocumentContent): string[] {
  const out = new Set<string>();
  for (const b of content.blocks) {
    if (b.kind === "org" && b.organisationId) out.add(b.organisationId);
  }
  return [...out];
}

/**
 * 組織ブロックの決めかた。
 * fixed … 様式で組織を決めてある / kind … 種別だけ決めてあり、組織は生成するときに選ぶ /
 * any … 種別も組織も生成するときに選ぶ
 */
export type OrgBlockMode = "fixed" | "kind" | "any";

export function orgBlockMode(b: {
  organisationId: string;
  organisationKind?: OrganisationKind;
}): OrgBlockMode {
  if (b.organisationId) return "fixed";
  return b.organisationKind ? "kind" : "any";
}

/** 生成するときに組織を選ばせるブロック（様式で決めていないもの）。並びは紙面の順 */
export function openOrgBlocks(
  content: DocumentContent,
): { id: string; kind: OrganisationKind | null }[] {
  return content.blocks.flatMap((b) =>
    b.kind === "org" && !b.organisationId ? [{ id: b.id, kind: b.organisationKind ?? null }] : [],
  );
}

/**
 * 生成するときに選んだ組織を URL で持ち回る形。`<ブロックid>:<組織id>` を並べる。
 * 読めないものは落とす
 */
export function parseOrgChoices(raw: string | string[] | undefined): Map<string, string> {
  const out = new Map<string, string>();
  for (const v of Array.isArray(raw) ? raw : raw ? [raw] : []) {
    const at = v.indexOf(":");
    if (at <= 0 || at === v.length - 1) continue;
    out.set(v.slice(0, at), v.slice(at + 1));
  }
  return out;
}

export function formatOrgChoices(choices: ReadonlyMap<string, string>): string[] {
  return [...choices].map(([blockId, orgId]) => `${blockId}:${orgId}`);
}

/** 選んだ組織をブロックへ書き込む。**様式で決めてあるものは触らない** */
export function applyOrgChoices(
  content: DocumentContent,
  choices: ReadonlyMap<string, string>,
): DocumentContent {
  return {
    ...content,
    blocks: content.blocks.map((b) => {
      if (b.kind !== "org" || b.organisationId) return b;
      const id = choices.get(b.id);
      return id ? { ...b, organisationId: id } : b;
    }),
  };
}

/** 項目名から、差込項目1つを組み立てる */
export function orgItemField(label: string, target: DocumentTarget): DocumentField {
  return {
    key: `${ORG_ITEM_PREFIX}${label}`,
    target,
    // 会社ごとに違う言葉なので、訳しようがない。打たれたものをそのまま出す
    labelJa: `所属する会社の${label}`,
    labelEn: `Your company: ${label}`,
  };
}

/** 宛先の自由項目 */
export function recipientItemField(label: string, target: DocumentTarget): DocumentField {
  return {
    key: `${RECIPIENT_ITEM_PREFIX}${label}`,
    target,
    labelJa: `宛先の${label}`,
    labelEn: `Recipient: ${label}`,
  };
}

/**
 * その対象で選べる項目。
 * `orgItems` に会社の項目名を渡すと、その分も選べるようになる
 */
export function fieldsFor(target: DocumentTarget, orgItems: string[] = []): DocumentField[] {
  return [
    ...DOCUMENT_FIELDS.filter((f) => f.target === target || f.target === "*"),
    ...orgItems.map((label) => orgItemField(label, target)),
    ...orgItems.map((label) => recipientItemField(label, target)),
    // 対象が組織なら、その組織の自由項目も
    ...(target === "ORGANISATION" ? orgItems.map((label) => targetOrgItemField(label)) : []),
  ];
}

/**
 * 鍵が、その対象で使えるものか。
 *
 * 会社の自由項目は、`orgItems` を渡さないかぎり**すべて使えるものとして扱う**。
 * 会社ごとに持っている項目が違い、「この会社には無い」は空欄で正しいため。
 * 一覧を渡したときだけ、そこに無いものを知らせる（テンプレートの点検用）
 */
export function isKnownField(target: DocumentTarget, key: string, orgItems?: string[]): boolean {
  for (const prefix of [ORG_ITEM_PREFIX, RECIPIENT_ITEM_PREFIX, TARGET_ORG_ITEM_PREFIX]) {
    if (!key.startsWith(prefix)) continue;
    if (prefix === TARGET_ORG_ITEM_PREFIX && target !== "ORGANISATION") return false;
    return orgItems === undefined || orgItems.includes(key.slice(prefix.length));
  }
  return DOCUMENT_FIELDS.some((f) => (f.target === target || f.target === "*") && f.key === key);
}

/**
 * 表のブロックが引くデータ。
 * **どれも画面にある表と同じもの。**帳票のために計算し直さない。
 */
export const DOCUMENT_TABLES = [
  "composition",
  "compositionAggregate",
  "judgement",
  "substanceRegulation",
  "substanceInventory",
] as const;
export type DocumentTable = (typeof DOCUMENT_TABLES)[number];

export interface DocumentTableDef {
  key: DocumentTable;
  target: DocumentTarget;
  labelJa: string;
  labelEn: string;
  /** 出せる列。並びも選べるので、鍵だけ持つ */
  columns: { key: string; labelJa: string; labelEn: string }[];
}

export const DOCUMENT_TABLE_DEFS: DocumentTableDef[] = [
  {
    key: "composition",
    target: "PRODUCT",
    labelJa: "組成",
    labelEn: "Composition",
    columns: [
      { key: "code", labelJa: "ID", labelEn: "ID" },
      { key: "casNumber", labelJa: "CAS番号", labelEn: "CAS" },
      { key: "name", labelJa: "物質名/原材料名", labelEn: "Name" },
      { key: "contentPct", labelJa: "重量%", labelEn: "Weight %" },
      { key: "note", labelJa: "備考", labelEn: "Note" },
    ],
  },
  {
    key: "compositionAggregate",
    target: "PRODUCT",
    labelJa: "原材料展開・CAS合算",
    labelEn: "Expanded and summed by CAS",
    columns: [
      { key: "casNumber", labelJa: "CAS番号", labelEn: "CAS" },
      { key: "code", labelJa: "物質ID", labelEn: "Substance ID" },
      { key: "name", labelJa: "物質名", labelEn: "Name" },
      { key: "totalPct", labelJa: "重量%", labelEn: "Weight %" },
      { key: "note", labelJa: "備考", labelEn: "Note" },
    ],
  },
  {
    key: "judgement",
    target: "PRODUCT",
    labelJa: "法規制判定",
    labelEn: "Regulation results",
    columns: [
      { key: "law", labelJa: "法律", labelEn: "Law" },
      { key: "category", labelJa: "規制区分", labelEn: "Category" },
      { key: "officialNumber", labelJa: "番号", labelEn: "Number" },
      { key: "statutoryName", labelJa: "法文物質名", labelEn: "Statutory name" },
      { key: "verdict", labelJa: "該非", labelEn: "Verdict" },
      { key: "needsReview", labelJa: "要確認", labelEn: "Needs review" },
    ],
  },
  {
    key: "substanceRegulation",
    target: "SUBSTANCE",
    labelJa: "該当法規",
    labelEn: "Applicable regulations",
    columns: [
      { key: "law", labelJa: "法律", labelEn: "Law" },
      { key: "category", labelJa: "規制区分", labelEn: "Category" },
      { key: "officialNumber", labelJa: "番号", labelEn: "Number" },
      { key: "statutoryName", labelJa: "法文物質名", labelEn: "Statutory name" },
    ],
  },
  {
    key: "substanceInventory",
    target: "SUBSTANCE",
    labelJa: "インベントリ番号",
    labelEn: "Inventory numbers",
    columns: [
      { key: "inventory", labelJa: "インベントリ", labelEn: "Inventory" },
      { key: "country", labelJa: "国", labelEn: "Country" },
      { key: "value", labelJa: "番号", labelEn: "Number" },
    ],
  },
];

export function tablesFor(target: DocumentTarget): DocumentTableDef[] {
  return DOCUMENT_TABLE_DEFS.filter((t) => t.target === target);
}

/**
 * 文字とその装飾。
 *
 * **エディタ（TipTap）が吐く形をそのまま持たない。**
 * ライブラリを替えたときにテンプレートが読めなくなるため、
 * こちらで決めた最小限の形に直してから保存する。
 */
export interface RichMark {
  bold?: boolean;
  italic?: boolean;
  underline?: boolean;
  /** `#112233`。指定が無ければ本文の色 */
  color?: string;
  /** ポイント数。指定が無ければブロックの既定 */
  size?: number;
}

/** 文中の一区切り。差込項目もここに混ざる */
export type RichSpan =
  ({ kind: "text"; text: string } & RichMark) | ({ kind: "field"; field: string } & RichMark);

/**
 * 組織ブロックの1行。
 *
 * **見出しは紙面の言葉で決める。**組織側の項目名（「担当者」）と、
 * 紙に出したい言葉（「ご担当」「Attn.」）は別もの。
 * 組織の項目名を変えると全部の様式が変わってしまうので、様式の側で持つ。
 *
 * 置き場所も行ごとに決める。宛名は左、差出人は右、といった置きかたのため
 */
export interface OrgBlockItem {
  /** 組織の項目名。`ORG_NAME_ITEM` は組織の名称そのもの */
  item: string;
  /** 紙に出す見出し。**空なら値だけ**を出す */
  label?: string;
  /** 行の寄せ。省略は左 */
  align?: "left" | "center" | "right";
}

/** 段落1つぶん */
export interface RichLine {
  spans: RichSpan[];
  align?: "left" | "center" | "right";
}

export const BLOCK_KINDS = [
  "heading",
  "text",
  "fields",
  "org",
  "table",
  "divider",
  "spacer",
  "rowBreak",
  "pageBreak",
  "signature",
  "image",
] as const;
export type BlockKind = (typeof BLOCK_KINDS)[number];

/** 画像の寄せ */
export const IMAGE_ALIGNS = ["left", "center", "right"] as const;
export type ImageAlign = (typeof IMAGE_ALIGNS)[number];

/**
 * ブロックの幅。
 *
 * **入れ子にしない。**「横並び」という入れものを作ると、
 * その中にまた入れられることになり、並べ替えも中と外で別々に要る。
 * かわりに1つずつ幅を持たせ、**幅の合計が1に収まるあいだ横に続ける**。
 * 並びは上から下のままなので、これまでの並べ替えがそのまま使える。
 */
/**
 * 昔の書き方。**読むだけ。**新しく作るものは％で持つ。
 * 既に保存されているテンプレートがこの形なので、捨てられない
 */
const LEGACY_WIDTH: Record<string, number> = {
  full: 100,
  twoThirds: 66,
  half: 50,
  third: 33,
};

/**
 * ブロックの幅。
 *
 *   数（5〜100） … その割合。100 は全幅
 *   "auto"       … 均等。**同じ行の均等どうしで、残りを等分する**
 *   昔の名前     … 読むためだけに残してある
 */
export type BlockWidth = number | "auto" | "full" | "twoThirds" | "half" | "third";

/** 選べる％。細かすぎると選ぶのが手間なので、よく使うものだけ並べる */
export const WIDTH_PERCENTS = [100, 75, 66, 60, 50, 40, 33, 25, 20] as const;

/** 打ち込める％の範囲。5未満は文字が入らず、幅として意味がない */
export const WIDTH_MIN = 5;
export const WIDTH_MAX = 100;

/** 幅を％の数にする。均等は数が決まらないので null */
export function widthPercent(w: BlockWidth | undefined): number | null {
  if (w === undefined) return 100;
  if (w === "auto") return null;
  if (typeof w === "number") return w;
  return LEGACY_WIDTH[w] ?? 100;
}

/** 幅として通る値か（保存する前に確かめる） */
export function isBlockWidth(v: unknown): v is BlockWidth {
  if (v === "auto") return true;
  if (typeof v === "string") return v in LEGACY_WIDTH;
  return typeof v === "number" && Number.isInteger(v) && v >= WIDTH_MIN && v <= WIDTH_MAX;
}

/** 行を絞る条件。値はどの列も文字として扱う */
export const TABLE_FILTER_OPS = [
  "contains",
  "notContains",
  "equals",
  "notEquals",
  "empty",
  "notEmpty",
  "matches",
] as const;
export type TableFilterOp = (typeof TABLE_FILTER_OPS)[number];

export interface TableFilter {
  column: string;
  op: TableFilterOp;
  /** `empty` / `notEmpty` では使わない */
  value?: string;
}

/**
 * 値の置き換え。
 * **正規表現で探して、当たったところを差し替える。**
 * 「該当」を「〇」にする、単位を落とす、といった紙面だけの整えに使う
 */
export interface TableReplacement {
  column: string;
  /** 探す形（正規表現） */
  pattern: string;
  /** 置き換える文字。`$1` で括弧の中を差し込める */
  replacement: string;
}

/** 打ち間違いで紙面が壊れないよう、読めない形は当てずに素通りさせる */
export function compileReplacement(r: TableReplacement): RegExp | null {
  if (r.pattern === "") return null;
  try {
    return new RegExp(r.pattern, "g");
  } catch {
    return null;
  }
}

/** その行を出すか */
export function passesFilter(cell: string, f: TableFilter): boolean {
  const v = f.value ?? "";
  switch (f.op) {
    case "contains":
      return cell.includes(v);
    case "notContains":
      return !cell.includes(v);
    case "equals":
      return cell === v;
    case "notEquals":
      return cell !== v;
    case "empty":
      return cell === "";
    case "notEmpty":
      return cell !== "";
    case "matches": {
      if (v === "") return true;
      try {
        return new RegExp(v).test(cell);
      } catch {
        // 読めない形は「絞らない」。打っている途中で行が消えると、直しようがない
        return true;
      }
    }
    default:
      return true;
  }
}

/**
 * 選べる書体。
 *
 * **決まったものから選ばせる。**書体名を打たせると、
 * その字が入っていない機械で刷ったときに別の字になり、行が折り返す位置まで変わる。
 *
 * **刷るのは利用者のパソコン**なので、そこに入っている書体しか出ない。
 * ゴシックと明朝は Windows・Mac のどちらにも入っている。
 * UD の2つは **Windows 10/11 には標準で入っているが Mac には無い**ので、
 * Mac で開くとゴシック・明朝に落ちる（並びの後ろがそのまま受け皿になる）。
 *
 * 保存するのは鍵（`gothic` など）。実際の書体の並びは後から差し替えられる
 */
const GOTHIC =
  '"Yu Gothic", "YuGothic", "Hiragino Kaku Gothic ProN", "Meiryo", "MS PGothic", sans-serif';
const MINCHO = '"Yu Mincho", "YuMincho", "Hiragino Mincho ProN", "MS PMincho", serif';

export const DOCUMENT_FONTS = [
  { key: "gothic", stack: GOTHIC },
  { key: "mincho", stack: MINCHO },
  { key: "udGothic", stack: `"BIZ UDPGothic", "BIZ UDPゴシック", ${GOTHIC}` },
  { key: "udMincho", stack: `"BIZ UDPMincho", "BIZ UDP明朝 Medium", ${MINCHO}` },
  /*
    2026-09-13 に増やした分。**入っていない機械では後ろの並びに落ちる。**
    メイリオ・ＭＳ ゴシック・ＭＳ 明朝は Windows に標準で入っている（Mac には無い）。
    Arial・Times New Roman は Windows・Mac の両方にある。英文の様式向け
  */
  { key: "meiryo", stack: `"Meiryo", "メイリオ", ${GOTHIC}` },
  { key: "msGothic", stack: `"MS Gothic", "ＭＳ ゴシック", "MS PGothic", ${GOTHIC}` },
  { key: "msMincho", stack: `"MS Mincho", "ＭＳ 明朝", "MS PMincho", ${MINCHO}` },
  { key: "arial", stack: `Arial, Helvetica, ${GOTHIC}` },
  { key: "times", stack: `"Times New Roman", Times, ${MINCHO}` },
] as const;

export type FontKey = (typeof DOCUMENT_FONTS)[number]["key"];

/** 余白の高さ。mm の数か、古い様式の3段 */
export type SpacerSize = number | "sm" | "md" | "lg";
/** 古い3段を mm に読み替える */
export function spacerMm(size: SpacerSize): number {
  if (typeof size === "number") return size;
  return { sm: 4, md: 8, lg: 16 }[size];
}

/** 見出しレベル。1〜6（2026-09-13 指示で 3 から増やした）。目次で階層を表すのに使う */
export const HEADING_LEVELS = [1, 2, 3, 4, 5, 6] as const;
export type HeadingLevel = (typeof HEADING_LEVELS)[number];

/** 紙面ぜんたいで何も選ばれていないときの書体 */
export const DEFAULT_FONT: FontKey = "gothic";

/** 鍵から、実際に当てる書体の並び。知らない鍵は既定（何も当てない） */
export function fontStack(key: string | undefined): string | undefined {
  return DOCUMENT_FONTS.find((f) => f.key === key)?.stack;
}

/**
 * ブロック全体の字。
 *
 * **どの種類のブロックにも付く。**表・項目の並び・組織・署名欄にも、
 * 大きさや色を決めたいことがある（注記だけ小さく、表題だけ色を変える）。
 *
 * 文章と見出しは、この上に**文字ごとの指定**（`RichMark`）を重ねられる。
 * ブロックの指定が土台で、文字ごとの指定が勝つ
 */
export interface BlockStyle {
  /** 書体。省略は紙面ぜんたいの指定に従う */
  family?: FontKey;
  /** ポイント数。省略は紙面の既定 */
  size?: number;
  bold?: boolean;
  italic?: boolean;
  underline?: boolean;
  /** `#112233`。省略は本文の色 */
  color?: string;
  /*
    ブロックの飾り（2026-09-13 指示）。字ではなく入れものに付く。
    背景色・背景の模様・枠線。どれかがあれば中身に少し余白を取る
  */
  /** 背景色 `#rrggbb` */
  background?: string;
  /** 背景の模様。色は patternColor（省略は薄い灰色） */
  pattern?: BlockPattern;
  patternColor?: string;
  /** 枠線の種類。省略は枠なし */
  borderStyle?: BlockBorderStyle;
  /** 枠線の太さ（mm）。省略は 0.3 */
  borderWidth?: number;
  /** 枠線の色。省略は黒 */
  borderColor?: string;
}

export const BLOCK_PATTERNS = ["stripes", "verticalStripes", "diagonal", "dots", "grid"] as const;
export type BlockPattern = (typeof BLOCK_PATTERNS)[number];

export const BLOCK_BORDER_STYLES = ["solid", "dashed", "dotted", "double"] as const;
export type BlockBorderStyle = (typeof BLOCK_BORDER_STYLES)[number];

/**
 * ブロックの余白（mm）。**紙の端、または隣のブロックからの間。**
 * 新しく置くブロックには4辺とも値を入れる（欄に出ている値がそのまま使われる。2026-09-13 決定）。
 * 古い様式のブロックは辺が抜けていることがあり、抜けた辺は `legacyBlockMargin` の値で補う
 */
export interface BlockMargin {
  top?: number;
  right?: number;
  bottom?: number;
  left?: number;
}

/**
 * 紙面ぜんたいの字の大きさの既定（pt）。本文（文章・項目・署名など）の大きさ。
 * いちばん上の欄には「既定」ではなくこの値を出し、**そのまま引き継がれる本当の値**として扱う（2026-09-14 決定）
 */
export const DEFAULT_FONT_SIZE = 10.5;
/** 見出しレベルごとの大きさ（pt）。紙面ぜんたいの大きさには従わず、ブロックの欄にこの値を既定として出す */
export const HEADING_SIZES: Record<HeadingLevel, number> = {
  1: 18,
  2: 16,
  3: 14,
  4: 12,
  5: 11,
  6: 10.5,
};
/** 表の中身の大きさ（pt）。本文より一段小さい。表のブロックの欄にこの値を既定として出す */
export const TABLE_FONT_SIZE = 9;

/**
 * 種類として自分の大きさを持つブロック（見出し・表）の既定（pt）。それ以外は undefined（紙面ぜんたいに従う）。
 * 編集者の意図（上で 10.5 と決めたのに見出しが 10.5 になっては困る）に合わせ、
 * 見出しはレベル、表は表用の値を持つ（2026-09-14 決定）。`kind` は紙面に出すときの種類でもよい
 */
export function ownFontSize(block: { kind: string; level?: HeadingLevel }): number | undefined {
  if (block.kind === "heading") return HEADING_SIZES[block.level ?? 2];
  if (block.kind === "table") return TABLE_FONT_SIZE;
  return undefined;
}

/** 新しく置くブロックの余白（mm）。上 0・右 0・下 3・左 0（2026-09-13 決定） */
export const DEFAULT_BLOCK_MARGIN: Required<BlockMargin> = { top: 0, right: 0, bottom: 3, left: 0 };

/**
 * 余白を書いていない（古い）ブロックの余白。
 * **種類ごとに決め打ちだった頃の値をそのまま使い、保存済みの様式の見た目を変えない。**
 * 新しいブロックは4辺とも書いてあるので、ここは通らない
 */
export function legacyBlockMargin(kind: MarginKind): Required<BlockMargin> {
  const none = { top: 0, right: 0, bottom: 0, left: 0 };
  switch (kind) {
    case "heading":
    case "text":
      return { ...none, bottom: 3 };
    case "fields":
    case "org":
    case "orgItems":
      return { ...none, bottom: 4 };
    case "table":
      return { ...none, bottom: 5 };
    case "divider":
      return { ...none, top: 4, bottom: 4 };
    case "signature":
      return { ...none, top: 8 };
    default:
      return none;
  }
}

/** 余白の決まりを引く鍵。様式のブロックの種類か、紙面に出すときの種類（組織は "orgItems" になる） */
export type MarginKind = BlockKind | "orgItems";

/** 実際に使う余白。書いてある辺はその値、書いていない辺は古い決まりの値 */
export function effectiveMargin(
  kind: MarginKind,
  margin: BlockMargin | undefined,
): Required<BlockMargin> {
  const legacy = legacyBlockMargin(kind);
  return {
    top: margin?.top ?? legacy.top,
    right: margin?.right ?? legacy.right,
    bottom: margin?.bottom ?? legacy.bottom,
    left: margin?.left ?? legacy.left,
  };
}

interface BlockBase {
  id: string;
  /** 省略は全幅。全幅のブロックは必ず1行を占める */
  width?: BlockWidth;
  /** そのブロックの字。省略は紙面の既定 */
  style?: BlockStyle;
  /** そのブロックの余白。新しいブロックは4辺とも入る。抜けた辺は `legacyBlockMargin` */
  margin?: BlockMargin;
}

export type DocumentBlock =
  /**
   * 見出し。`level` は見出しレベル（1 がいちばん上。目次や番号付けで階層を表すためのもの）。
   * 字の大きさを指定していないときの既定の大きさもレベルで決まる
   */
  | (BlockBase & { kind: "heading"; level: HeadingLevel; lines: RichLine[] })
  | (BlockBase & { kind: "text"; lines: RichLine[] })
  /** 「ラベル：値」を縦に並べたもの */
  /**
   * 項目の並び（「ラベル：値」を縦に並べる）。
   * `labelStyle` はラベルだけの字（ブロックの字の上に重ねる）、`gap` はラベルと値の間（mm）。
   * どちらも省略なら、字はブロックのまま・間は 6mm（2026-09-13 指示で足した）
   */
  | (BlockBase & {
      kind: "fields";
      items: { label: string; field: string }[];
      labelStyle?: BlockStyle;
      gap?: number;
      /** 値の寄せ。右にすると値が右端にそろう（狭い枠で氏名が折れるのを避ける）。省略は左 */
      valueAlign?: "left" | "right";
      /** ラベルの位置。右にすると「値 ラベル」の並びになる（2026-09-16 指示）。省略は左 */
      labelPosition?: "left" | "right";
      /** ラベルの幅（ブロックの横幅に対する %）。空なら中身の長さぶん */
      labelWidth?: number;
    })
  /**
   * 名指しした組織の項目を並べる。
   *
   * **差出人・宛先とは別もの。**あちらは「帳票を作る人／相手」で、
   * 誰が作るか・誰に出すかで中身が変わる。こちらは**様式に組織を書き込む**もので、
   * 「問い合わせ先はいつも品質保証部」のように、相手によらず決まっているものを置く。
   *
   * `items` に並べるのは項目名。`ORG_NAME_ITEM` だけは組織の名称そのものを指す
   */
  | (BlockBase & {
      kind: "org";
      /**
       * どの組織か。**空なら様式では決めず、生成するときに選ぶ。**
       * `organisationKind` があれば、その種別の中から選ばせる
       */
      organisationId: string;
      /** 生成するときに選ばせる種別。組織を決めてあるときは見ない */
      organisationKind?: OrganisationKind;
      /** 出す項目。並びはこの配列の順 */
      items: OrgBlockItem[];
    })
  | (BlockBase & {
      kind: "table";
      table: DocumentTable;
      /** 出す列。**並びはここで決まる**（選んだ順ではなく、この配列の順） */
      columns: string[];
      /**
       * 出していない列も含めた並び（編集画面の一覧の順）。チェックを外しても場所を保つため（2026-09-16 指示）。
       * 無ければ columns の順のあとに定義の順で続く
       */
      columnOrder?: string[];
      caption?: string;
      /** 出す行を絞る。複数あるときは、すべてに当てはまる行だけを出す */
      filters?: TableFilter[];
      /** 出す値を置き換える。上から順に当てる */
      replacements?: TableReplacement[];
    })
  | (BlockBase & { kind: "divider" })
  /**
   * 余白。`size` は高さ。**mm の数で持つ**（2026-09-13 指示で自由に打てるようにした）。
   * 古い様式の "sm" | "md" | "lg" もそのまま読める（4・8・16 mm）
   */
  | (BlockBase & { kind: "spacer"; size: SpacerSize })
  /** ここで横並びを終える。紙には何も出ない（改ページと違い、紙は変わらない） */
  | (BlockBase & { kind: "rowBreak" })
  | (BlockBase & { kind: "pageBreak" })
  /**
   * 署名欄。`labelPosition` はラベルを線の左に置くか上に置くか（省略は左）、
   * `gap` はラベルと線の間（mm、省略は 4）、`lineWidth` は線の長さ（mm、省略は 60）。
   * 2026-09-13 指示で決められるようにした
   */
  | (BlockBase & {
      kind: "signature";
      label: string;
      labelPosition?: "left" | "above";
      gap?: number;
      lineWidth?: number;
    })
  /**
   * 画像（ロゴ・印影・写真）。**画像ライブラリの画像を id で指す**（2026-09-16 指示）。
   * 幅・高さは mm。片方だけなら縦横比で決まり、両方空なら元の大きさ（紙幅を超えれば縮む）
   */
  | (BlockBase & {
      kind: "image";
      imageId: string;
      widthMm?: number;
      heightMm?: number;
      /** 幅と高さを縦横の比で連動させるか（編集画面のリンクの印。省略は連動）。紙面には影響しない */
      keepRatio?: boolean;
      align?: ImageAlign;
    });

/** 様式が使っている画像の id（印刷用ページで中身を埋め込むため） */
export function imageIdsIn(content: DocumentContent): string[] {
  const ids = new Set<string>();
  for (const b of content.blocks) if (b.kind === "image" && b.imageId) ids.add(b.imageId);
  return [...ids];
}

/**
 * 横に並ぶものをまとめる。**画面と紙面の両方がこれを使う。**
 * 別々に組むと、編集画面で見えている並びと出てきた紙が食い違う。
 *
 * 改ページは必ず1行を占める。途中に挟まると、横並びが分断されて読めなくなる。
 */
export interface BlockRow<T> {
  blocks: T[];
  index: number[];
  /** その行で実際に使う幅（％）。均等はここで数が決まる */
  percents: number[];
}

export function groupIntoRows<T extends { kind: string; width?: BlockWidth }>(
  blocks: T[],
): BlockRow<T>[] {
  const rows: BlockRow<T>[] = [];
  let current: BlockRow<T> | null = null;
  /** その行で、数の決まっているものが使っている割合 */
  let filled = 0;

  blocks.forEach((b, i) => {
    const pct = widthPercent(b.width);
    // 全幅と改ページは1行を占める。途中に挟まると横並びが分断されて読めなくなる
    /*
      全幅・改ページ・改行は1行を占める。
      改行は**そこで横並びを終わらせるためだけ**にあり、紙には何も出ない。
      幅の合計が100%に届かなくても、意図した場所で折り返せる
    */
    const alone = pct === 100 || b.kind === "pageBreak" || b.kind === "rowBreak";
    /*
      均等は場所を取らない扱いで詰めていき、行が決まってから残りを分ける。
      **決まっている幅で100%が埋まっていたら、均等は次の行へ。**
      入れても幅が0になるだけで、置く意味が無い
    */
    const needs = pct ?? 0;
    const noRoom = pct === null ? filled >= 99.999 : filled + needs > 100.001;

    if (alone || current === null || noRoom) {
      current = { blocks: [b], index: [i], percents: [] };
      rows.push(current);
      filled = alone ? 100 : needs;
      return;
    }
    current.blocks.push(b);
    current.index.push(i);
    filled += needs;
  });

  // 行が決まってから、均等のぶんを分ける
  for (const row of rows) {
    const fixed = row.blocks.map((b) => widthPercent(b.width));
    const autos = fixed.filter((p) => p === null).length;
    const used = fixed.reduce((a: number, p) => a + (p ?? 0), 0);
    const share = autos > 0 ? Math.max(0, 100 - used) / autos : 0;
    row.percents = fixed.map((p) => p ?? share);
  }
  return rows;
}

/** テンプレートの中身そのもの */
export interface DocumentContent {
  /** 出す紙の向き。印刷のCSSに渡す */
  orientation: "portrait" | "landscape";
  /**
   * 紙面ぜんたいの字。**各ブロックの既定になる。**
   * ブロックの側で指定があれば、そちらが勝つ
   */
  style?: BlockStyle;
  blocks: DocumentBlock[];
}

export const EMPTY_DOCUMENT: DocumentContent = { orientation: "portrait", blocks: [] };

/**
 * 保存されている JSON を、こちらの形として読めるか確かめる。
 *
 * **読めない中身は、黙って捨てずに知らせる。**
 * テンプレートは人が作ったものなので、
 * 開いたら空になっていた、では何が起きたのか分からない。
 */
export function parseDocumentContent(value: unknown): DocumentContent | null {
  if (typeof value !== "object" || value === null) return null;
  const v = value as Partial<DocumentContent>;
  if (v.orientation !== "portrait" && v.orientation !== "landscape") return null;
  if (!Array.isArray(v.blocks)) return null;
  for (const b of v.blocks) {
    if (typeof b !== "object" || b === null) return null;
    const kind = (b as DocumentBlock).kind;
    if (!(BLOCK_KINDS as readonly string[]).includes(kind)) return null;
    if (typeof (b as DocumentBlock).id !== "string") return null;
    /*
      幅は**通らない値なら落とす。**読めない幅で描くと崩れるだけなので、
      全幅として扱う（省略と同じ）。テンプレートごと読めなくするほどではない
    */
    const w = (b as DocumentBlock).width;
    if (w !== undefined && !isBlockWidth(w)) delete (b as DocumentBlock).width;
    /*
      組織ブロックの**古い形**（項目名を並べただけ）を読めるようにする。
      作り直させると、保存済みの様式が開けなくなる
    */
    if (kind === "org") {
      const ob = b as { items?: unknown };
      if (Array.isArray(ob.items)) {
        ob.items = ob.items.map((x) => (typeof x === "string" ? { item: x } : x));
      }
    }
  }
  return v as DocumentContent;
}

/**
 * テンプレートが使っている差込項目のうち、その対象では使えないものを返す。
 * **対象を後から変えたときに気づけるようにする。**
 */
export function unknownFields(
  content: DocumentContent,
  target: DocumentTarget,
  orgItems?: string[],
): string[] {
  const out = new Set<string>();
  const check = (key: string) => {
    if (!isKnownField(target, key, orgItems)) out.add(key);
  };
  for (const b of content.blocks) {
    if (b.kind === "fields") {
      for (const it of b.items) check(it.field);
    } else if (b.kind === "heading" || b.kind === "text") {
      for (const line of b.lines) {
        for (const s of line.spans) if (s.kind === "field") check(s.field);
      }
    } else if (b.kind === "table") {
      const def = DOCUMENT_TABLE_DEFS.find((t) => t.key === b.table);
      if (!def || def.target !== target) out.add(`table:${b.table}`);
    }
  }
  return [...out];
}

/**
 * テンプレートの入れもの（中身の JSON を除いた部分）。
 *
 * **中身は別に扱う。**ブロックの並びは編集画面が丸ごと差し替えるので、
 * 名前や対象を直すのと同じ入口にすると、片方だけ保存したいときに困る。
 */
export const documentTemplateSchema = (m: Messages) =>
  z.object({
    code: z.string().trim().min(1, m.validation.required).max(50, m.validation.tooLong(50)),
    nameJa: z.string().trim().min(1, m.validation.required).max(200, m.validation.tooLong(200)),
    nameEn: z.string().trim().max(200, m.validation.tooLong(200)).nullish(),
    target: z.enum(DOCUMENT_TARGETS),
    /**
     * 作りかた。**あとから変えられる。**
     * 画面で組んだものを Excel に替えても、ブロックの並びは残しておく
     * （替え間違えたときに戻せるようにするため）
     */
    kind: z.enum(DOCUMENT_TEMPLATE_KINDS),
    locale: z.string().trim().min(1, m.validation.required).max(10, m.validation.tooLong(10)),
    active: z.boolean(),
    /**
     * 宛先を差し込む様式か。
     * **印が付いている様式でだけ、作るときに宛先を選ばせる**
     */
    usesRecipient: z.boolean(),
    note: z.string().trim().max(2000, m.validation.tooLong(2000)).nullish(),
  });

export type DocumentTemplateInput = z.infer<ReturnType<typeof documentTemplateSchema>>;
