import { z } from "zod";
import type { Messages } from "./i18n/ja";

/**
 * ドキュメント生成のテンプレート。
 *
 * テンプレートは**システムの中で作る**（Wordファイルは使わない）。
 * 中身はここで決めた形の JSON で、`document_templates.content` に入る。
 *
 * ## なぜ Word ではないのか
 *
 * Word に差し込む形だと、`{product.cod}` のような打ち間違いを
 * 登録のときに検査する仕組みが別に要る。
 * **項目を一覧から選ばせれば、無い項目は書きようがない。**
 *
 * ## 出す形に引きずられないこと
 *
 * ここに置くのは「何を、どの順で出すか」だけ。
 * HTML にするのか .docx にするのかは、出す側（レンダラ）が決める。
 * **JSON に出力形式のことを書かない。**書くと、出し先が増えるたびに
 * 作ったテンプレートを作り直すことになる。
 */

/** テンプレートが何を1件受け取るか */
export const DOCUMENT_TARGETS = ["PRODUCT", "SUBSTANCE"] as const;
export type DocumentTarget = (typeof DOCUMENT_TARGETS)[number];

/**
 * 差込項目。**エディタの選択肢と、差し込む側の両方がここを見る。**
 * 片方にしか無い項目ができると、選べるのに空欄になる（またはその逆）。
 */
export interface DocumentField {
  /** `product.code` のような鍵。テンプレート JSON に入る */
  key: string;
  /** どの対象のときに選べるか */
  target: DocumentTarget;
  /** 選択肢に出す名前。画面の言語で出し分けるので2つ持つ */
  labelJa: string;
  labelEn: string;
}

/**
 * 使える差込項目の一覧。
 *
 * **画面が出しているものだけを並べる。**画面に無い値をここに足すと、
 * 帳票のためだけにデータを引く道ができてしまい、画面と食い違う元になる。
 */
export const DOCUMENT_FIELDS: DocumentField[] = [
  // --- 共通（どちらの対象でも出せるもの） ---
  { key: "doc.generatedAt", target: "PRODUCT", labelJa: "作成日時", labelEn: "Generated at" },
  { key: "doc.generatedBy", target: "PRODUCT", labelJa: "作成者", labelEn: "Generated by" },
  { key: "doc.version", target: "PRODUCT", labelJa: "法規制のバージョン", labelEn: "Version" },
  { key: "doc.generatedAt", target: "SUBSTANCE", labelJa: "作成日時", labelEn: "Generated at" },
  { key: "doc.generatedBy", target: "SUBSTANCE", labelJa: "作成者", labelEn: "Generated by" },
  { key: "doc.version", target: "SUBSTANCE", labelJa: "法規制のバージョン", labelEn: "Version" },

  // --- 製品 ---
  { key: "product.code", target: "PRODUCT", labelJa: "製品コード", labelEn: "Product code" },
  { key: "product.nameJa", target: "PRODUCT", labelJa: "日本語名称", labelEn: "Name (JA)" },
  { key: "product.nameEn", target: "PRODUCT", labelJa: "英語名称", labelEn: "Name (EN)" },
  { key: "product.modelName", target: "PRODUCT", labelJa: "型式", labelEn: "Model" },
  { key: "product.useName", target: "PRODUCT", labelJa: "用途", labelEn: "Use" },
  { key: "product.note", target: "PRODUCT", labelJa: "備考", labelEn: "Note" },
  {
    key: "product.judgementCount",
    target: "PRODUCT",
    labelJa: "該当した規制区分の数",
    labelEn: "Applicable categories",
  },

  // --- 物質 ---
  { key: "substance.code", target: "SUBSTANCE", labelJa: "物質コード", labelEn: "Substance code" },
  { key: "substance.casNumber", target: "SUBSTANCE", labelJa: "CAS番号", labelEn: "CAS number" },
  { key: "substance.nameJa", target: "SUBSTANCE", labelJa: "日本語名", labelEn: "Name (JA)" },
  { key: "substance.nameEn", target: "SUBSTANCE", labelJa: "英語名", labelEn: "Name (EN)" },
  { key: "substance.note", target: "SUBSTANCE", labelJa: "備考", labelEn: "Note" },
];

/** その対象で選べる項目 */
export function fieldsFor(target: DocumentTarget): DocumentField[] {
  return DOCUMENT_FIELDS.filter((f) => f.target === target);
}

/** 鍵が、その対象で使えるものか */
export function isKnownField(target: DocumentTarget, key: string): boolean {
  return DOCUMENT_FIELDS.some((f) => f.target === target && f.key === key);
}

/**
 * 表のブロックが引くデータ。
 * **どれも画面にある表と同じもの。**帳票のために計算し直さない。
 */
export const DOCUMENT_TABLES = [
  "composition",
  "compositionAggregate",
  "judgement",
  "substanceRegulation",
  "substanceInventory",
] as const;
export type DocumentTable = (typeof DOCUMENT_TABLES)[number];

export interface DocumentTableDef {
  key: DocumentTable;
  target: DocumentTarget;
  labelJa: string;
  labelEn: string;
  /** 出せる列。並びも選べるので、鍵だけ持つ */
  columns: { key: string; labelJa: string; labelEn: string }[];
}

export const DOCUMENT_TABLE_DEFS: DocumentTableDef[] = [
  {
    key: "composition",
    target: "PRODUCT",
    labelJa: "組成",
    labelEn: "Composition",
    columns: [
      { key: "code", labelJa: "ID", labelEn: "ID" },
      { key: "casNumber", labelJa: "CAS番号", labelEn: "CAS" },
      { key: "name", labelJa: "物質名/原材料名", labelEn: "Name" },
      { key: "contentPct", labelJa: "重量%", labelEn: "Weight %" },
      { key: "note", labelJa: "備考", labelEn: "Note" },
    ],
  },
  {
    key: "compositionAggregate",
    target: "PRODUCT",
    labelJa: "原材料展開・CAS合算",
    labelEn: "Expanded and summed by CAS",
    columns: [
      { key: "casNumber", labelJa: "CAS番号", labelEn: "CAS" },
      { key: "code", labelJa: "物質ID", labelEn: "Substance ID" },
      { key: "name", labelJa: "物質名", labelEn: "Name" },
      { key: "totalPct", labelJa: "重量%", labelEn: "Weight %" },
      { key: "note", labelJa: "備考", labelEn: "Note" },
    ],
  },
  {
    key: "judgement",
    target: "PRODUCT",
    labelJa: "法規制判定",
    labelEn: "Regulation results",
    columns: [
      { key: "law", labelJa: "法律", labelEn: "Law" },
      { key: "category", labelJa: "規制区分", labelEn: "Category" },
      { key: "officialNumber", labelJa: "番号", labelEn: "Number" },
      { key: "statutoryName", labelJa: "法文物質名", labelEn: "Statutory name" },
      { key: "verdict", labelJa: "該非", labelEn: "Verdict" },
      { key: "needsReview", labelJa: "要確認", labelEn: "Needs review" },
    ],
  },
  {
    key: "substanceRegulation",
    target: "SUBSTANCE",
    labelJa: "該当法規",
    labelEn: "Applicable regulations",
    columns: [
      { key: "law", labelJa: "法律", labelEn: "Law" },
      { key: "category", labelJa: "規制区分", labelEn: "Category" },
      { key: "officialNumber", labelJa: "番号", labelEn: "Number" },
      { key: "statutoryName", labelJa: "法文物質名", labelEn: "Statutory name" },
    ],
  },
  {
    key: "substanceInventory",
    target: "SUBSTANCE",
    labelJa: "インベントリ番号",
    labelEn: "Inventory numbers",
    columns: [
      { key: "inventory", labelJa: "インベントリ", labelEn: "Inventory" },
      { key: "country", labelJa: "国", labelEn: "Country" },
      { key: "value", labelJa: "番号", labelEn: "Number" },
    ],
  },
];

export function tablesFor(target: DocumentTarget): DocumentTableDef[] {
  return DOCUMENT_TABLE_DEFS.filter((t) => t.target === target);
}

/**
 * 文字とその装飾。
 *
 * **エディタ（TipTap）が吐く形をそのまま持たない。**
 * ライブラリを替えたときにテンプレートが読めなくなるため、
 * こちらで決めた最小限の形に直してから保存する。
 */
export interface RichMark {
  bold?: boolean;
  italic?: boolean;
  underline?: boolean;
  /** `#112233`。指定が無ければ本文の色 */
  color?: string;
  /** ポイント数。指定が無ければブロックの既定 */
  size?: number;
}

/** 文中の一区切り。差込項目もここに混ざる */
export type RichSpan =
  ({ kind: "text"; text: string } & RichMark) | ({ kind: "field"; field: string } & RichMark);

/** 段落1つぶん */
export interface RichLine {
  spans: RichSpan[];
  align?: "left" | "center" | "right";
}

export const BLOCK_KINDS = [
  "heading",
  "text",
  "fields",
  "table",
  "divider",
  "spacer",
  "pageBreak",
  "signature",
] as const;
export type BlockKind = (typeof BLOCK_KINDS)[number];

export type DocumentBlock =
  | { id: string; kind: "heading"; level: 1 | 2 | 3; lines: RichLine[] }
  | { id: string; kind: "text"; lines: RichLine[] }
  /** 「ラベル：値」を縦に並べたもの */
  | { id: string; kind: "fields"; items: { label: string; field: string }[] }
  | { id: string; kind: "table"; table: DocumentTable; columns: string[]; caption?: string }
  | { id: string; kind: "divider" }
  | { id: string; kind: "spacer"; size: "sm" | "md" | "lg" }
  | { id: string; kind: "pageBreak" }
  | { id: string; kind: "signature"; label: string };

/** テンプレートの中身そのもの */
export interface DocumentContent {
  /** 出す紙の向き。印刷のCSSに渡す */
  orientation: "portrait" | "landscape";
  blocks: DocumentBlock[];
}

export const EMPTY_DOCUMENT: DocumentContent = { orientation: "portrait", blocks: [] };

/**
 * 保存されている JSON を、こちらの形として読めるか確かめる。
 *
 * **読めない中身は、黙って捨てずに知らせる。**
 * テンプレートは人が作ったものなので、
 * 開いたら空になっていた、では何が起きたのか分からない。
 */
export function parseDocumentContent(value: unknown): DocumentContent | null {
  if (typeof value !== "object" || value === null) return null;
  const v = value as Partial<DocumentContent>;
  if (v.orientation !== "portrait" && v.orientation !== "landscape") return null;
  if (!Array.isArray(v.blocks)) return null;
  for (const b of v.blocks) {
    if (typeof b !== "object" || b === null) return null;
    const kind = (b as DocumentBlock).kind;
    if (!(BLOCK_KINDS as readonly string[]).includes(kind)) return null;
    if (typeof (b as DocumentBlock).id !== "string") return null;
  }
  return v as DocumentContent;
}

/**
 * テンプレートが使っている差込項目のうち、その対象では使えないものを返す。
 * **対象を後から変えたときに気づけるようにする。**
 */
export function unknownFields(content: DocumentContent, target: DocumentTarget): string[] {
  const out = new Set<string>();
  const check = (key: string) => {
    if (!isKnownField(target, key)) out.add(key);
  };
  for (const b of content.blocks) {
    if (b.kind === "fields") {
      for (const it of b.items) check(it.field);
    } else if (b.kind === "heading" || b.kind === "text") {
      for (const line of b.lines) {
        for (const s of line.spans) if (s.kind === "field") check(s.field);
      }
    } else if (b.kind === "table") {
      const def = DOCUMENT_TABLE_DEFS.find((t) => t.key === b.table);
      if (!def || def.target !== target) out.add(`table:${b.table}`);
    }
  }
  return [...out];
}

/**
 * テンプレートの入れもの（中身の JSON を除いた部分）。
 *
 * **中身は別に扱う。**ブロックの並びは編集画面が丸ごと差し替えるので、
 * 名前や対象を直すのと同じ入口にすると、片方だけ保存したいときに困る。
 */
export const documentTemplateSchema = (m: Messages) =>
  z.object({
    code: z.string().trim().min(1, m.validation.required).max(50, m.validation.tooLong(50)),
    nameJa: z.string().trim().min(1, m.validation.required).max(200, m.validation.tooLong(200)),
    nameEn: z.string().trim().max(200, m.validation.tooLong(200)).nullish(),
    target: z.enum(DOCUMENT_TARGETS),
    locale: z.string().trim().min(1, m.validation.required).max(10, m.validation.tooLong(10)),
    active: z.boolean(),
    displayOrder: z.number().int().min(0).max(9999),
    note: z.string().trim().max(2000, m.validation.tooLong(2000)).nullish(),
  });

export type DocumentTemplateInput = z.infer<ReturnType<typeof documentTemplateSchema>>;
